on: push

name: Compute scores

jobs:
  render:
    name: Compute scores
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - name: Install Dependencies
        run: |
            Rscript -e 'install.packages(c("dplyr", "jsonlite"))'
      - name: Run script to make data
        run: Rscript -e 'source("analysis/make_scores.R")'

      - name: Commit results
        run: |
          git add variables_scores.js
          git commit variables_scores.js -m 'Make variables_scores.js' || echo "No changes to commit"
          git push origin || echo "No changes to commit"